org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
java_version=25
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.94
neo_version_range=[26.1.2.94]
loader_version_range=[4,)
ae2_version=26.1.10-beta
ae2_version_range=[26.1.10-beta,27)
mod_id=ae2lightoptimizer
mod_name=AE2LO - Applied Energistics 2 Lightweight Optimization / 应用能源 2 轻量优化
mod_license=All Rights Reserved
mod_version=0.0.2
mod_group_id=com.example.ae2lightoptimizer
