package com.example.ae2loprobe;

import appeng.api.config.Actionable;
import appeng.api.crafting.IPatternDetails;
import appeng.api.ids.AEComponents;
import appeng.api.networking.IGrid;
import appeng.api.stacks.AEItemKey;
import appeng.api.stacks.AEKey;
import appeng.api.stacks.KeyCounter;
import appeng.crafting.execution.CraftingCpuHelper;
import appeng.crafting.inv.ListCraftingInventory;
import appeng.me.helpers.MachineSource;
import com.example.ae2lightoptimizer.block.CraftingRipperBlockEntity;
import com.example.ae2lightoptimizer.integration.CraftingRipperPatterns;
import com.example.ae2lightoptimizer.item.ModItems;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.serialization.JsonOps;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import net.minecraft.SharedConstants;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.core.registries.Registries;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.packs.PackType;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.CustomData;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.level.storage.LevelResource;
import net.neoforged.neoforge.common.crafting.DataComponentIngredient;

/** Real isolated-world datapack reloads; the live server recipe is the independent output oracle. */
public final class PackRecipeReloadFixture {
    public static final boolean ENABLED = "pack_catalog".equals(System.getProperty("ae2lo.probe.chain"));
    private static final String NS = "ae2lo_pack_probe";
    private static final String PACK = "ae2lo_pack_catalog_probe";
    private static final int SETTLE_TICKS = 80;
    private static final Map<String, Object> report = new LinkedHashMap<>();
    private static final List<Map<String, Object>> phases = new ArrayList<>();
    private static final List<Map<String, Object>> reloads = new ArrayList<>();
    private static final Map<String, AEItemKey> previousOutputs = new LinkedHashMap<>();
    private static ServerLevel level;
    private static IGrid grid;
    private static CraftingRipperBlockEntity ripper;
    private static Path output;
    private static Path packDirectory;
    private static List<String> originalPacks;
    private static CompletableFuture<Void> reloadFuture;
    private static Map<AEKey, Long> stockBefore;
    private static Map<String, Object> currentReload;
    private static long stageTick;
    private static long reloadStarted;
    private static int stage;
    private static int pendingStage;
    private static boolean finished;
    private static String failure;
    private static ItemStack exactA;
    private static ItemStack exactB;

    private PackRecipeReloadFixture() { }

    public static void begin(ServerLevel serverLevel, IGrid activeGrid, CraftingRipperBlockEntity block, Path evidence) {
        if (level != null) return;
        level = serverLevel;
        grid = activeGrid;
        ripper = block;
        output = evidence.resolve("pack-catalog-report.json");
        try {
            require(level.getServer().getWorldData().getLevelName().startsWith("AE2LO-Ripper-Probe-"),
                    "Datapack fixture may only change its newly created probe world");
            originalPacks = List.copyOf(level.getServer().getPackRepository().getSelectedIds());
            var datapacks = level.getServer().getWorldPath(LevelResource.DATAPACK_DIR).toAbsolutePath().normalize();
            packDirectory = datapacks.resolve(PACK).normalize();
            require(packDirectory.startsWith(datapacks) && !Files.exists(packDirectory), "Probe datapack path is occupied or unsafe");
            Files.createDirectories(packDirectory);
            report.put("world", level.getServer().getWorldData().getLevelName());
            report.put("scenario", "Live server RecipeManager and AE network publication across real pack insertion, replacement, tag change, removal and restoration");
            report.put("boundary", "Standard crafting/smithing/stonecutting JSON and NeoForge components ingredient, as generated by pack scripts. No KubeJS engine is installed or claimed; no crafting order is submitted by this fixture.");
            report.put("independentOracle", "RecipeManager.byKey + real matches/assemble. Actual grid.getCraftingFor candidates supply their native input selector and validateInputs; production catalog builders are never called.");
            report.put("originalSelectedPacks", originalPacks);
            report.put("probePackDirectory", packDirectory.toString());
            report.put("phases", phases);
            report.put("reloads", reloads);
            exactA = exactPaper(7);
            exactB = exactPaper(8);
            var stock = new ArrayList<ItemStack>();
            for (var item : List.of(Items.REDSTONE, Items.LAPIS_LAZULI, Items.PAPER, Items.IRON_INGOT,
                    Items.STONE, Items.ANDESITE, Items.GUNPOWDER, Items.OAK_PLANKS, Items.GOLD_INGOT)) stock.add(item.getDefaultInstance());
            stock.add(exactA);
            stock.add(exactB);
            var inserted = new ArrayList<Map<String, Object>>();
            for (var stack : stock) {
                var key = AEItemKey.of(stack);
                long accepted = grid.getStorageService().getInventory().insert(key, 32, Actionable.MODULATE, new MachineSource(ripper));
                require(accepted == 32, "Could not insert finite pack witness stock");
                inserted.add(Map.of("key", describe(stack), "amount", accepted));
            }
            report.put("finiteInputStock", inserted);
            stockBefore = stock();
            for (int i = 0; i < ripper.getLogic().getPatternInv().size(); i++) ripper.getLogic().getPatternInv().setItemDirect(i, ItemStack.EMPTY);
            ripper.getUpgrades().setItemDirect(0, ModItems.LOOP_CARD.get().getDefaultInstance());
            stageTick = level.getGameTime();
            write();
        } catch (Throwable problem) { fail(problem); }
    }

    public static void tick() {
        if (level == null || finished) return;
        try {
            if (reloadFuture != null) {
                if (!reloadFuture.isDone()) return;
                reloadFuture.join();
                reloadFuture = null;
                currentReload.put("completed", true);
                currentReload.put("milliseconds", (System.nanoTime() - reloadStarted) / 1_000_000.0);
                currentReload.put("newRecipeManagerIdentity", System.identityHashCode(level.getServer().getRecipeManager()));
                stage = pendingStage;
                stageTick = level.getGameTime();
                write();
                return;
            }
            if (level.getGameTime() - stageTick < SETTLE_TICKS) return;
            if (stage == 0) {
                var phase = phase("baseline");
                require(knownRecipe(NS + ":tag_shapeless") == null, "Probe namespace already has a recipe");
                audit(phase, new Witness("minecraft:stick", RecipeType.CRAFTING, frame(Items.OAK_PLANKS.getDefaultInstance(), 0,
                        Items.OAK_PLANKS.getDefaultInstance(), 3), Items.STICK, 4, null));
                audit(phase, new Witness("minecraft:gold_nugget", RecipeType.CRAFTING, frame(Items.GOLD_INGOT.getDefaultInstance(), 0), Items.GOLD_NUGGET, 9, null));
                writePack(1);
                reload(1, true);
            } else if (stage == 1) {
                auditPack(1);
                writePack(2);
                reload(2, true);
            } else if (stage == 2) {
                auditPack(2);
                reload(3, false);
            } else if (stage == 3) {
                var phase = phase("restored_original_packs");
                for (String id : customIds()) absent(phase, id);
                audit(phase, new Witness("minecraft:stick", RecipeType.CRAFTING, frame(Items.OAK_PLANKS.getDefaultInstance(), 0,
                        Items.OAK_PLANKS.getDefaultInstance(), 3), Items.STICK, 4, null));
                audit(phase, new Witness("minecraft:gold_nugget", RecipeType.CRAFTING, frame(Items.GOLD_INGOT.getDefaultInstance(), 0), Items.GOLD_NUGGET, 9, null));
                require(new LinkedHashSet<>(level.getServer().getPackRepository().getSelectedIds()).equals(new LinkedHashSet<>(originalPacks)),
                        "Original selected datapacks were not restored");
                require(stockBefore.equals(stock()), "Directory-only fixture changed real ME item stock");
                report.put("originalPacksRestored", true);
                report.put("realItemStockUnchanged", true);
                finished = true;
                write();
            } else if (stage == 4) {
                report.put("originalPacksRestoredAfterFailure", true);
                finished = true;
                write();
            }
        } catch (Throwable problem) { fail(problem); }
    }

    private static void auditPack(int version) {
        var phase = phase(version == 1 ? "pack_loaded" : "recipes_and_tags_replaced");
        Item material = version == 1 ? Items.REDSTONE : Items.LAPIS_LAZULI;
        Item oldMaterial = version == 1 ? Items.LAPIS_LAZULI : Items.REDSTONE;
        Item rock = version == 1 ? Items.STONE : Items.ANDESITE;
        Item oldRock = version == 1 ? Items.ANDESITE : Items.STONE;
        audit(phase, new Witness(NS + ":tag_shapeless", RecipeType.CRAFTING, frame(material.getDefaultInstance(), 0),
                version == 1 ? Items.PRISMARINE_SHARD : Items.PRISMARINE_CRYSTALS, version == 1 ? 3 : 2,
                frame(oldMaterial.getDefaultInstance(), 0)));
        audit(phase, new Witness(NS + ":tag_shaped", RecipeType.CRAFTING,
                frame(material.getDefaultInstance(), 0, Items.PAPER.getDefaultInstance(), 1), Items.RABBIT_HIDE, 1,
                frame(oldMaterial.getDefaultInstance(), 0, Items.PAPER.getDefaultInstance(), 1)));
        audit(phase, new Witness(NS + ":tag_smithing", RecipeType.SMITHING,
                frame(Items.PAPER.getDefaultInstance(), 3, Items.IRON_INGOT.getDefaultInstance(), 4, material.getDefaultInstance(), 5),
                Items.NAUTILUS_SHELL, 1,
                frame(Items.PAPER.getDefaultInstance(), 3, Items.IRON_INGOT.getDefaultInstance(), 4, oldMaterial.getDefaultInstance(), 5)));
        audit(phase, new Witness(NS + ":tag_stonecutting", RecipeType.STONECUTTING, frame(rock.getDefaultInstance(), 4), Items.FLINT, 2,
                frame(oldRock.getDefaultInstance(), 4)));
        audit(phase, new Witness(NS + ":exact_components", RecipeType.CRAFTING, frame(exactA, 0), Items.HEART_OF_THE_SEA, 1, frame(exactB, 0)));
        audit(phase, new Witness("minecraft:stick", RecipeType.CRAFTING, frame(Items.PAPER.getDefaultInstance(), 0),
                version == 1 ? Items.INK_SAC : Items.GLOW_INK_SAC, version == 1 ? 2 : 4,
                frame(Items.OAK_PLANKS.getDefaultInstance(), 0, Items.OAK_PLANKS.getDefaultInstance(), 3)));
        if (version == 1) {
            audit(phase, new Witness(NS + ":removed_on_reload", RecipeType.CRAFTING, frame(Items.GUNPOWDER.getDefaultInstance(), 0), Items.FERMENTED_SPIDER_EYE, 1, null));
            audit(phase, new Witness("minecraft:gold_nugget", RecipeType.CRAFTING, frame(Items.GOLD_INGOT.getDefaultInstance(), 0), Items.GOLD_NUGGET, 9, null));
        } else {
            absent(phase, NS + ":removed_on_reload");
            absent(phase, "minecraft:gold_nugget");
        }
    }

    private static void audit(Map<String, Object> phase, Witness witness) {
        var holder = knownRecipe(witness.id());
        require(holder != null, "Server RecipeManager omitted " + witness.id());
        var recipe = holder.value();
        require(recipe.getType() == witness.type(), "Live RecipeType changed for " + witness.id());
        require(matches(recipe, witness.input()), "Live recipe rejected intended input for " + witness.id());
        var expected = assemble(recipe, witness.input());
        require(expected.is(witness.output()) && expected.getCount() == witness.count(), "Independent assemble result differs for " + witness.id());
        var key = AEItemKey.of(expected);
        var candidates = grid.getCraftingService().getCraftingFor(key).stream().filter(pattern -> witness.id().equals(recipeId(pattern))).toList();
        var row = new LinkedHashMap<String, Object>();
        rows(phase).add(row);
        row.put("recipeId", witness.id());
        row.put("recipeType", recipe.getType().toString());
        row.put("nativeRecipeClass", recipe.getClass().getName());
        row.put("inputs", witness.input().stream().map(PackRecipeReloadFixture::describe).toList());
        row.put("expected", describe(expected));
        row.put("actualCandidateCount", candidates.size());
        row.put("actualCandidateClasses", candidates.stream().map(pattern -> pattern.getClass().getName()).distinct().toList());
        require(!candidates.isEmpty(), "AE network omitted custom/reloaded recipe " + witness.id());
        boolean accepted = false;
        for (var pattern : candidates) {
            var extracted = extract(pattern, witness.input());
            if (extracted != null) {
                require(CraftingRipperPatterns.validateInputs(pattern, extracted, level), "Actual network candidate failed exact live input validation: " + witness.id());
                require(pattern.getPrimaryOutput().what().equals(key) && pattern.getPrimaryOutput().amount() == expected.getCount(),
                        "Actual published output quantity differs from assemble");
                accepted = true;
            }
        }
        require(accepted, "No actual published candidate accepts the independently matched input " + witness.id());
        row.put("actualCandidateInputsValidated", true);
        if (witness.id().equals(NS + ":exact_components")) {
            for (var pattern : candidates) {
                require(pattern.getInputs().length == 1, "Exact component recipe has unexpected input shape");
                require(pattern.getInputs()[0].isValid(AEItemKey.of(exactA), level), "Actual IInput rejected the exact custom_data witness");
                require(!pattern.getInputs()[0].isValid(AEItemKey.of(exactB), level), "Actual IInput accepted wrong deep custom_data");
                require(!pattern.getInputs()[0].isValid(AEItemKey.of(Items.PAPER), level), "Actual IInput accepted component-free paper");
            }
            row.put("actualIInputExactCustomData", Map.of("sourceA", true, "sourceB", false, "plainPaper", false));
        }
        if (witness.rejected() != null) {
            require(!matches(recipe, witness.rejected()), "Live recipe accepted deliberately wrong tag/component input " + witness.id());
            for (var pattern : candidates) require(extract(pattern, witness.rejected()) == null,
                    "Actual network candidate accepts wrong tag/component input " + witness.id());
            row.put("rejectedInputs", witness.rejected().stream().map(PackRecipeReloadFixture::describe).toList());
            row.put("nativeAndActualCandidatesRejectWrongInput", true);
        }
        var previous = previousOutputs.put(witness.id(), key);
        if (previous != null && !previous.equals(key)) {
            long stale = grid.getCraftingService().getCraftingFor(previous).stream().filter(pattern -> witness.id().equals(recipeId(pattern))).count();
            row.put("oldOutputCandidateCount", stale);
            require(stale == 0, "AE network retained old output after replacement: " + witness.id());
        }
        row.put("passed", true);
    }

    private static KeyCounter[] extract(IPatternDetails pattern, List<ItemStack> input) {
        var inventory = new ListCraftingInventory(ignored -> { });
        for (var stack : input) if (!stack.isEmpty()) inventory.insert(AEItemKey.of(stack), stack.getCount(), Actionable.MODULATE);
        return CraftingCpuHelper.extractPatternInputs(pattern, inventory, level, new KeyCounter(), new KeyCounter());
    }

    private static void absent(Map<String, Object> phase, String id) {
        require(knownRecipe(id) == null, "Removed recipe remains in server RecipeManager: " + id);
        long retained = ripper.getLogic().getAvailablePatterns().stream().filter(pattern -> id.equals(recipeId(pattern))).count();
        var oldOutput = previousOutputs.get(id);
        long published = oldOutput == null ? 0 : grid.getCraftingService().getCraftingFor(oldOutput).stream().filter(pattern -> id.equals(recipeId(pattern))).count();
        rows(phase).add(Map.of("recipeId", id, "absentFromServer", true, "retainedProviderPatterns", retained, "oldNetworkCandidates", published));
        require(retained == 0 && published == 0, "Removed recipe still advertised in AE network: " + id);
    }

    private static void writePack(int version) throws java.io.IOException {
        var metadata = new JsonObject();
        var pack = new JsonObject();
        pack.addProperty("description", "AE2LO isolated pack catalog acceptance; temporary test world only");
        var format = SharedConstants.getCurrentVersion().packVersion(PackType.SERVER_DATA);
        pack.add("min_format", json(List.of(format.major(), format.minor())));
        pack.add("max_format", json(List.of(format.major(), format.minor())));
        metadata.add("pack", pack);
        if (version == 2) metadata.add("filter", json(Map.of("block", List.of(Map.of("namespace", "minecraft", "path", "recipe/gold_nugget\\.json")))));
        file("pack.mcmeta", metadata);
        file("data/" + NS + "/tags/item/material.json", json(Map.of("replace", true, "values", List.of(version == 1 ? "minecraft:redstone" : "minecraft:lapis_lazuli"))));
        file("data/" + NS + "/tags/item/rocks.json", json(Map.of("replace", true, "values", List.of(version == 1 ? "minecraft:stone" : "minecraft:andesite"))));
        recipe(NS, "tag_shapeless", shapeless(List.of(ingredient("#" + NS + ":material")), version == 1 ? "minecraft:prismarine_shard" : "minecraft:prismarine_crystals", version == 1 ? 3 : 2));
        recipe(NS, "tag_shaped", json(Map.of("type", "minecraft:crafting_shaped", "category", "misc", "pattern", List.of("MP"),
                "key", Map.of("M", ingredient("#" + NS + ":material"), "P", ingredient("minecraft:paper")), "result", result("minecraft:rabbit_hide", 1))));
        recipe(NS, "tag_smithing", json(Map.of("type", "minecraft:smithing_transform", "template", ingredient("minecraft:paper"),
                "base", ingredient("minecraft:iron_ingot"), "addition", ingredient("#" + NS + ":material"), "result", result("minecraft:nautilus_shell", 1))));
        recipe(NS, "tag_stonecutting", json(Map.of("type", "minecraft:stonecutting", "ingredient", ingredient("#" + NS + ":rocks"), "result", result("minecraft:flint", 2))));
        var exact = DataComponentIngredient.of(false, DataComponents.CUSTOM_DATA, exactA.get(DataComponents.CUSTOM_DATA), Items.PAPER);
        var ops = RegistryOps.create(JsonOps.INSTANCE, level.registryAccess());
        var exactJson = Ingredient.CODEC.encodeStart(ops, exact).getOrThrow().getAsJsonObject();
        var componentJson = exactJson.getAsJsonObject("components");
        var defaultJsonData = CustomData.CODEC.parse(JsonOps.INSTANCE, componentJson.get("minecraft:custom_data")).getOrThrow();
        var intendedData = exactA.get(DataComponents.CUSTOM_DATA);
        report.put("defaultJsonNumericCustomData", defaultJsonData.copyTag().toString());
        report.put("defaultJsonPreservesIntWitness", intendedData.equals(defaultJsonData));
        // JsonOps converts small JSON numbers to narrower NBT tags. The native SNBT alternative
        // preserves the intended IntTag and all other nested NBT types without weakening matching.
        componentJson.addProperty("minecraft:custom_data", intendedData.copyTag().toString());
        var decodedData = CustomData.CODEC.parse(JsonOps.INSTANCE, componentJson.get("minecraft:custom_data")).getOrThrow();
        var decodedIngredient = Ingredient.CODEC.parse(ops, exactJson).getOrThrow();
        require(intendedData.equals(decodedData), "SNBT ingredient changed typed custom_data");
        require(decodedIngredient.test(exactA) && !decodedIngredient.test(exactB)
                && !decodedIngredient.test(Items.PAPER.getDefaultInstance()), "Serialized native ingredient changed exact component acceptance");
        byte intendedTagType = ((CompoundTag) intendedData.copyTag().get("deep")).get("value").getId();
        byte decodedTagType = ((CompoundTag) decodedData.copyTag().get("deep")).get("value").getId();
        require(intendedTagType == 3 && decodedTagType == 3, "Integer witness did not retain its native IntTag type");
        report.put("serializedExactIngredientRoundTrip", Map.of("typedCustomDataEqual", true,
                "intendedTagId", intendedTagType, "decodedTagId", decodedTagType,
                "sourceA", true, "sourceB", false, "plainPaper", false));
        recipe(NS, "exact_components", shapeless(List.of(exactJson), "minecraft:heart_of_the_sea", 1));
        report.put("nativeEncodedExactIngredient", exactJson);
        recipe("minecraft", "stick", shapeless(List.of(ingredient("minecraft:paper")), version == 1 ? "minecraft:ink_sac" : "minecraft:glow_ink_sac", version == 1 ? 2 : 4));
        if (version == 1) recipe(NS, "removed_on_reload", shapeless(List.of(ingredient("minecraft:gunpowder")), "minecraft:fermented_spider_eye", 1));
        else Files.delete(packDirectory.resolve("data/" + NS + "/recipe/removed_on_reload.json"));
    }

    private static void reload(int nextStage, boolean includeProbePack) {
        var server = level.getServer();
        server.getPackRepository().reload();
        var selected = new ArrayList<>(originalPacks);
        if (includeProbePack) {
            require(server.getPackRepository().getAvailableIds().contains("file/" + PACK), "Native pack repository did not discover the test datapack");
            selected.add("file/" + PACK);
        }
        currentReload = new LinkedHashMap<>();
        currentReload.put("targetStage", nextStage);
        currentReload.put("selectedPacks", selected);
        currentReload.put("oldRecipeManagerIdentity", System.identityHashCode(server.getRecipeManager()));
        reloads.add(currentReload);
        pendingStage = nextStage;
        reloadStarted = System.nanoTime();
        write();
        reloadFuture = server.reloadResources(selected);
    }

    private static JsonElement ingredient(String id) { return json(id); }
    private static Map<String, Object> result(String id, int count) { return Map.of("id", id, "count", count); }
    private static JsonElement shapeless(List<JsonElement> ingredients, String output, int count) {
        return json(Map.of("type", "minecraft:crafting_shapeless", "category", "misc", "ingredients", ingredients, "result", result(output, count)));
    }
    private static JsonElement json(Object value) { return new GsonBuilder().create().toJsonTree(value); }
    private static void recipe(String namespace, String id, JsonElement content) throws java.io.IOException { file("data/" + namespace + "/recipe/" + id + ".json", content); }
    private static void file(String relative, JsonElement content) throws java.io.IOException {
        var path = packDirectory.resolve(relative).normalize();
        require(path.startsWith(packDirectory), "Unsafe probe resource path");
        Files.createDirectories(path.getParent());
        Files.writeString(path, new GsonBuilder().setPrettyPrinting().create().toJson(content));
    }

    private static RecipeHolder<?> knownRecipe(String id) { return level.getServer().getRecipeManager().byKey(ResourceKey.create(Registries.RECIPE, Identifier.parse(id))).orElse(null); }
    private static boolean matches(Recipe<?> recipe, List<ItemStack> input) {
        if (recipe instanceof CraftingRecipe crafting) return crafting.matches(CraftingInput.of(3, 3, input), level);
        if (recipe instanceof SmithingRecipe smithing) return smithing.matches(new SmithingRecipeInput(input.get(3), input.get(4), input.get(5)), level);
        return recipe instanceof StonecutterRecipe stone && stone.matches(new SingleRecipeInput(input.get(4)), level);
    }
    private static ItemStack assemble(Recipe<?> recipe, List<ItemStack> input) {
        if (recipe instanceof CraftingRecipe crafting) return crafting.assemble(CraftingInput.of(3, 3, input));
        if (recipe instanceof SmithingRecipe smithing) return smithing.assemble(new SmithingRecipeInput(input.get(3), input.get(4), input.get(5)));
        return ((StonecutterRecipe) recipe).assemble(new SingleRecipeInput(input.get(4)));
    }
    private static String recipeId(IPatternDetails pattern) {
        if (pattern instanceof com.example.ae2lightoptimizer.integration.CatalogSmithingPattern smithing) return smithing.recipeId();
        var crafting = pattern.getDefinition().get(AEComponents.ENCODED_CRAFTING_PATTERN);
        if (crafting != null) return crafting.recipeId().identifier().toString();
        var smithing = pattern.getDefinition().get(AEComponents.ENCODED_SMITHING_TABLE_PATTERN);
        if (smithing != null) return smithing.recipeId().identifier().toString();
        var stone = pattern.getDefinition().get(AEComponents.ENCODED_STONECUTTING_PATTERN);
        return stone == null ? "<other>" : stone.recipeId().identifier().toString();
    }
    private static Map<String, Object> phase(String name) {
        var row = new LinkedHashMap<String, Object>();
        row.put("phase", name);
        row.put("tick", level.getGameTime());
        row.put("settledTicks", level.getGameTime() - stageTick);
        row.put("recipeManagerIdentity", System.identityHashCode(level.getServer().getRecipeManager()));
        row.put("serverRecipeCount", level.getServer().getRecipeManager().getRecipes().size());
        row.put("allowedServerRecipes", level.getServer().getRecipeManager().getRecipes().stream().filter(holder -> {
            var type = holder.value().getType();
            return type == RecipeType.CRAFTING || type == RecipeType.SMITHING || type == RecipeType.STONECUTTING;
        }).map(holder -> Map.of("id", holder.id().identifier().toString(), "type", holder.value().getType().toString(), "class", holder.value().getClass().getName())).toList());
        row.put("checks", new ArrayList<Map<String, Object>>());
        phases.add(row);
        return row;
    }
    @SuppressWarnings("unchecked") private static List<Map<String, Object>> rows(Map<String, Object> phase) { return (List<Map<String, Object>>) phase.get("checks"); }
    private static List<String> customIds() { return List.of("tag_shapeless", "tag_shaped", "tag_smithing", "tag_stonecutting", "exact_components", "removed_on_reload").stream().map(id -> NS + ":" + id).toList(); }
    private static List<ItemStack> frame(Object... entries) {
        var result = new ArrayList<>(Collections.nCopies(9, ItemStack.EMPTY));
        for (int i = 0; i < entries.length; i += 2) result.set((Integer) entries[i + 1], ((ItemStack) entries[i]).copy());
        return result;
    }
    private static ItemStack exactPaper(int value) {
        var inner = new CompoundTag();
        inner.putInt("value", value);
        var tag = new CompoundTag();
        tag.put("deep", inner);
        var stack = Items.PAPER.getDefaultInstance();
        stack.set(DataComponents.CUSTOM_DATA, CustomData.of(tag));
        return stack;
    }
    private static Map<String, Object> describe(ItemStack stack) {
        return stack.isEmpty() ? Map.of("empty", true) : Map.of("item", BuiltInRegistries.ITEM.getKey(stack.getItem()).toString(),
                "count", stack.getCount(), "components", stack.getComponentsPatch().toString());
    }
    private static Map<AEKey, Long> stock() {
        var result = new LinkedHashMap<AEKey, Long>();
        for (var entry : grid.getStorageService().getInventory().getAvailableStacks()) if (entry.getLongValue() > 0) result.put(entry.getKey(), entry.getLongValue());
        return result;
    }
    private static void require(boolean condition, String message) { if (!condition) throw new IllegalStateException(message); }
    private static void fail(Throwable problem) {
        if (failure == null) failure = problem.toString();
        else report.put("cleanupFailure", problem.toString());
        report.put("failure", failure);
        try {
            if (originalPacks != null && stage != 4 && pendingStage != 4) {
                reloadFuture = null;
                reload(4, false);
            } else finished = true;
        } catch (Throwable cleanup) { report.put("cleanupFailure", cleanup.toString()); finished = true; }
        write();
    }
    private static void write() {
        if (output == null) return;
        report.put("finished", finished);
        report.put("passed", passed());
        try { Files.createDirectories(output.getParent()); Files.writeString(output, new GsonBuilder().setPrettyPrinting().create().toJson(report)); }
        catch (java.io.IOException problem) { throw new java.io.UncheckedIOException(problem); }
    }
    public static boolean isFinished() { return finished; }
    public static boolean passed() { return finished && failure == null; }
    public static Map<String, Object> summary() {
        return Map.of("passed", passed(), "finished", finished, "phaseCount", phases.size(), "reloadCount", reloads.size(),
                "boundary", "Real pack reload and actual AE network candidates, no submitted order", "failure", failure == null ? "" : failure);
    }
    private record Witness(String id, RecipeType<?> type, List<ItemStack> input, Item output, int count, List<ItemStack> rejected) { }
}
